### ISSUE TITLE
Overlapping one text layer by other text layers

### ISSUE THREAD

**Issue by Andrey-VI** [mapnik/mapnik-support#1]
Want something like this: http://binged.it/RFCpkW. Layer with country names lies in background and other text layers lies above it. But I can't find in Mapnik an option to create text layer which can be overlapped by all other text layers. "allow-overlap" doesn't work this way. Did I miss something?

**Comment by springmeyer** [comment]
hmm, `allow-overlap` should work for doing that. I am aware that `allow-overlap` would not work currently if the `BELARUS` text used `placement:line` because I think with `line` placement allow-overlap is not respected the same way (need to confirm). But it should work with `placement:point`. What are you seeing happen - just no text showing up?

**Comment by Andrey-VI** [comment]
Yes, no text above country names. I have polygon layer with country names and placement="interior" option in the stylesheet.
And if allow-overlap="true" used, some country names overlap each other (inside one Rule). Is this right behavior?

**Comment by springmeyer** [comment]
seems to work fine with this testcase below.

however setting `allow-overlap` on the `front` style is not really optimal because then that text can overlap with itself. To solve this we could either modify mapnik to use named cached for collision (to control which symbolizers relate) or we could support `ignore-placement` for text so that you could set that on the `back` style as per mapnik/mapnik#1535

``` xml
<!DOCTYPE Map>
<Map background-color="#b5d0d0" srs="+init=epsg:4326" minimum-version="0.7.2">

    <Style name="points">
        <Rule>
            <MarkersSymbolizer width="40" ignore-placement="true"/>
        </Rule>
    </Style>

    <Layer name="points" srs="+init=epsg:4326">
        <StyleName>points</StyleName>
        <Datasource>
            <Parameter name="inline">
            x,y
            0,0
            0,5
            5,0
            5,5
            </Parameter>
            <Parameter name="type">csv</Parameter>
        </Datasource>
    </Layer>

    <Style name="back">
        <Rule>
            <TextSymbolizer size="100" fill="white" face-name="DejaVu Sans Book">[name]</TextSymbolizer>
        </Rule>
    </Style>

    <Layer name="back" srs="+init=epsg:4326">
        <StyleName>back</StyleName>
        <Datasource>
            <Parameter name="inline">
            x,y,name
            2.5,2.5,BELARUS
            </Parameter>
            <Parameter name="type">csv</Parameter>
        </Datasource>
    </Layer>

    <Style name="front">
        <Rule>
            <TextSymbolizer wrap-width="5" size="20" allow-overlap="true" face-name="DejaVu Sans Book">[name]</TextSymbolizer>
        </Rule>
    </Style>

    <Layer name="front" srs="+init=epsg:4326">
        <StyleName>front</StyleName>
        <Datasource>
            <Parameter name="inline">
            x,y,name
            1,2.5,"placename label"
            2.5,2.5,"placename label"
            4,2.5,"placename label"
            </Parameter>
            <Parameter name="type">csv</Parameter>
        </Datasource>
    </Layer>

</Map>
```

**Comment by springmeyer** [comment]
above XML gives:

<img src="http://f.cl.ly/items/0M421l0i3c0X3V1b203m/t.png" />

**Comment by Andrey-VI** [comment]
OK, I see.
So, there are two problems here:
1. Setting `allow-overlap` leads to overlapping text within style with this option enabled.
2. If you have a dozen of `front` styles with `allow-overlap="true"` then they will overlap each other.
`ignore-placement` sounds promising in this case.

**Comment by springmeyer** [comment]
great, will close, please follow mapnik/mapnik#1535.
