### ISSUE TITLE
m=h PNGs with mod_tile and renderd

### ISSUE THREAD

**Issue by Andrey-VI** [mapnik/mapnik-support#10]
Hello!
How to configure mod_tile and/or renderd to produce hextree quantized PNGs? Hope this is possible. It seems that default output is png256 with other options set by default. In that case image looks not as good as with png256:m=h.

**Comment by springmeyer** [comment]
I think renderd hardcodes this in the c code. So you will have to change the code. Ideally it would not be hardcoded, but it has been that way for a long time - before mapnik supported hextree mode.

**Comment by Andrey-VI** [comment]
OK. I found one cpp-file with png256 setting in the code: http://svn.openstreetmap.org/applications/utils/mod_tile/gen_tile.cpp. Is this it?

29.03.2013, 21:04, "Dane Springmeyer" notifications@github.com:

**Comment by springmeyer** [comment]
I'm not sure (/cc @apmon) but I would presume you are best off changing both of the occurrences of `"png256"` to `png8:m=h` to get the rendering quality you want.

**Comment by apmon** [comment]
Yes, I believe that is the correct file to change.

The two occurrences are due to a #ifdef compile level distinction between metatiles and non-metatiles. The metatile part is the default, and I am not sure if the non-metatile branch still works.

You suggest not to hard code it? Any suggesstions on where best to make it configurable?

**Comment by Andrey-VI** [comment]
Thank you Dane and @apmon.
