### ISSUE TITLE
Mapnik-iOS: Can not render png images on iPad

### ISSUE THREAD

**Issue by wibrahim** [mapnik/mapnik-support#16]
Running on iPad2 with iOS 6 installed I get this error:

```
Mapnik LOG>  could not intialize reader for: '/var/mobile/Applications/3C25E760-5838-479D-B981-3092CE503371/MB Example.app/aerodrome.png'
```

it works fine on iOS Simulator.

**Comment by rghosh0** [comment]
Is it another case of trying to write to a file in a directory where writing isn't permitted?

It reminds me of this problem that you had a few months ago:
https://github.com/mapnik/mapnik-support/issues/13#issuecomment-17906893

In that case, also, the action worked in the simulator but not on the device.  The application bundle directory is read-only, so trying to write to a png there will be expected to fail.

**Comment by wibrahim** [comment]
But it is not trying to write to a png, it's trying to read the png file. The png image is used to be rendered as part of the tile generated by mapnik. The error message I am getting stating that it failed to initialize "reader" for the png file, so I am certain it is not related to the file permission.
There was a fix for this issue before the release of mapnik 2.2.0 by calling `mapnik::register_image_reader` and providing a custom png_reader implementation. This interface method `mapnik::register_image_reader` no longer exists in v2.2.0 and not sure why.

**Comment by rghosh0** [comment]
I see.  Sorry for my misunderstanding.  Could the problem be related to XCode png compression?  I've ready about people having differing results in the simulator vs. on the device when dealing with png images, due to XCode's own png compression.

E.g. http://stackoverflow.com/questions/11634596/png-images-ok-on-simulator-but-dont-display-on-device
(This is not precisely the same problem as your own, but I wonder if it may be related?)

**Comment by springmeyer** [comment]
> There was a fix for this issue before the release of mapnik 2.2.0 by calling mapnik::register_image_reader and providing a custom png_reader implementation

Yes, this is the problem you are hitting. The workaround is still the same - that you need to call it yourself. Tracking this issue at https://github.com/mapnik/mapnik/issues/811. The cause is using a static libmapnik.a which ends up stripping this code. I've heard that ios8 supports dynamic libraries, so that may be another workaround?
