### ISSUE TITLE
What is faster: render from local PostGIS or from a shapefile

### ISSUE THREAD

**Issue by alasarr** [mapnik/mapnik-support#32]
I'm using Mapnik to generate tiles, so I'm making lots of render requests. I've written this library for that: https://github.com/GeographicaGS/Equidna.

The question is: what is faster as datasource a shapefile or a local PostGIS database?
I think the access to the data is faster with a shapefile, but PostGIS has really good spatial indexes so I think sometimes PostGIS would be better when lot's of operations geometries operations are involved (for example clipping, intersections, etc...).

Before start doing lots of benchmarking I'd like to know what are your thoughts about that.

Thanks in advance.

**Comment by wilhelmberg** [comment]
Depends on your data:

If you have just a few shape files with little data in them, stay with shape files.

If you have lots of geometries and/or cover a big area, PostGIS is highly recommended.

It gives you a lot more control over your data, by using the `z()` and `labelgrid()` functions in your SQL statements.
Available here: https://github.com/mapbox/postgis-vt-util

With those you can drastically limit the data that is delivered to mapnik (especially at low zoom levels) and make rendering much faster.

e.g.:
If you have 10,000 points that would fall within the extent of one tile at z8, it doesn't make sense to let mapnik render them, because they cannot be distinguished in the final image anyway.
`labelgrid()` let's you decide how many points should be rendered.

**Comment by wilhelmberg** [comment]
@alasarr  there are some new resources available, that show you how to use reduce the data coming from PostGIS:
https://www.mapbox.com/blog/postgis-sql-studio/

**Comment by alasarr** [comment]
Thanks a lot for the answers!

**Comment by BorisHollas** [comment]
What are "just a few shape files with little data in them"? I have shapefiles for 10 m and 50 m contour lines for 4 CGIAR regions (merged in one with gdalwarp -multi).

**Comment by wilhelmberg** [comment]
For 4 CGIAR regions and 10m contour lines I would definitely recommend using PostGIS.
That way you are able to control what data gets displayed when at a much more granular way.
e.g. it doesn't make sense to display 10m contour lines at zoom level 10.

**Comment by BorisHollas** [comment]
Indeed, but I can set minzoom to 15 in the properties for the shapefile. I assume this prevents mapnik from loading the shapefile at zoom level 10.

**Comment by wilhelmberg** [comment]
@BorisHollas 

> Indeed, but I can set minzoom to 15 in the properties for the shapefile. I assume this prevents mapnik from loading the shapefile at zoom level 10.

Correct!
But with PostGIS you could show 10m equi distance at a certain zoom level, 20m at another and then 50m and then 100m.
You can achieve the same with shapefiles but you would have to split them into several files.
