### ISSUE TITLE
Mapnik Windows build resource consumption

### ISSUE THREAD

**Issue by pmezard** [mapnik/mapnik-support#36]
Hello,

We have been happy mapnik users for more than a year but are now hitting some issue trying to upgrade our 2.2.x version. We build mapnik as a debug and release static library with Visual Studio 2010 and are trying to move to Visual Studio 2013. After updating to 2.2.x branch tip, with boost 1.56 and enabling spirit v3 we now fail to compile it, because of resource consumption. The debug build fails at the link step. We use a custom cmake script instead of Scons and hit something like:

```
[build] LINK : fatal error LNK1201: error writing to program database 'xxx\mapnik-vc100_x64-mt-gd.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
    [build] LINK Pass 1 failed. with 1201
    [build] ninja: build stopped: subcommand failed.
```

I have skimmed the Scons script and while we do not use the exact same option set, I saw nothing related to scaling the link part. The build machines are correct i7 boxes with 8G of memory and at least 20G of free space on SSD drives.

I am not sure you can really help us, I just wanted to point the mapnik build is a real beast to compile resource wise, cl.exe process often skyrockets to 1.5G to 2G of memory and mspdbsrv.exe easily grows past 2.5G, at least in debug build. I would not be suprised if it were related to using boost.spirit or similar libraries, the parsing modules being the most noticeable.

Is it something the mapnik team is aware of? For us it is becoming a technical issue just to build the library.

For now, we will try to downgrade to boost 1.55, compile it with VS2013 and stick with our previous mapnik snapshot, but assuming it works, it does not sound like a long term solution.

Thank you for any feedback about this problem.

**Comment by wilhelmberg** [comment]
Hello @pmezard thanks for your feeback

> I just wanted to point the mapnik build is a real beast to compile

So true.
We are aware of the problem, but still looking for effective solutions.
This is CPU usage for compiling latest mapnik 3.x on a 16 CPU machine (with sometimes up to 10GB memory usage):
![image](https://cloud.githubusercontent.com/assets/4549888/6584749/bcdc92c2-c76d-11e4-81aa-77dca68ee98b.png)

> LINK : fatal error LNK1201: error writing to program database

Have you tried cleaning all pdb files manually before attempting a new build?
I've come across this error when a build was interrupted and some process still held a reference to the pdb.
Mainly when building from within VS GUI.

> we now fail to compile it, because of resource consumption
> We use a custom cmake script instead

What type of project are you creating with CMake?
Make file or SLN file?
With SLN you could use MSBuild and explicitly set the [`m` (maxcpucount) switch of MSBuild](https://msdn.microsoft.com/en-us/library/bb651793.aspx) to 1 in order to eliminate parallel compiling.

```
msbuild YOUR.SLN /m:1 /p:BuildInParallel=false
```

> The debug build fails at the link step

I also faced problems with debug builds and switched to compiling `Release` with debug symbols (pdb) enabled.
Maybe that's something you might try, too?

---

In case you are adventurous :smirk: and want to try mapnik 3.x you could give https://github.com/mapbox/windows-builds a try.

Compiling (mapnik and all dependencies) should be as easy as:
https://github.com/mapbox/windows-builds#64bit

**But, you will need at least VS2014 CTP4 or VS2015CTP5, as mapnik 3.x makes heavy use of C++11 features!**
Users with no VS installed will also need the corresponding vcredist installed.

Please, do **not** install latest VS2015 CTP **6**, it sent my dev machine into nirvana.

---

Recent mapnik 3.x binaries are here (compiled with VS2014 CTP4):

64bit
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-631-gc1e947b.7z
https://mapnik.s3.amazonaws.com/dist/dev/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x64.exe

32bit
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x86-v3.0.0-rc1-631-gc1e947b.7z
https://mapnik.s3.amazonaws.com/dist/dev/visual-studio-runtimes/vcredist-VS2014-CTP4/vcredist_x86.exe

**Comment by pmezard** [comment]
Thank you for the answer.

On 10/03/15 22:31, Wilhelm Berg wrote:

> Have you tried cleaning all pdb files manually before attempting a new build?
> I've come across this error when a build was interrupted and some process still held a reference to the pdb.
> Mainly when building from within VS GUI.

Yes, this happens too when compiling from command line, and I cleaned the PDBs and even the other build products before restarting, to no avail.

> ```
> we now fail to compile it, because of resource consumption
> We use a custom cmake script instead
> ```

We generate a ninja build file, using cmake 3.x with custom rules (we also generate SLN but I did not try to build with those). Our production mapnik build works with up to 3 parallel processes, beyond that it completely destroys the build machine, but it is "correct". I tried the new build with a single process and it does not help wrt the link error.

> What type of project are you creating with CMake?
> Make file or SLN file?
> With SLN you could use MSBuild and explicitly set the |m| (maxcpucount) switch of MSBuild https://msdn.microsoft.com/en-us/library/bb651793.aspx to 1 in order to eliminate parallel compiling.
> 
> |msbuild YOUR.SLN /m:1 /p:BuildInParallel=false
> |
> 
> ```
> The debug build fails at the link step
> ```
> 
> I also faced problems with debug builds and switched to compiling |Release| with debug symbols (pdb) enabled.
> Maybe that's something you might try, too?

OK, I might try that. It is just a bit more work to specialize this one project but thanks for the suggestion.

> ---
> 
> In case you are adventurous :smirk: and want to try mapnik 3.x you could give https://github.com/mapbox/windows-builds a try.
> 
> Compiling (mapnik and all dependencies) should be as easy as:
> https://github.com/mapbox/windows-builds#64bit
> 
> _But, you will need at least VS2014 CTP4 or VS2015CTP5, as mapnik 3.x makes heavy use of C++11 features!_
> Users with no VS installed will also need the corresponding vcredist installed.
> 
> Please, do _not_ install latest VS2015 CTP _6_, it sent my dev machine into nirvana.

I am afraid I will not have the time to attempt this now, or at least I would rather complete the VS2013 migration first. We still have a lot of other dependencies to rebuild besides mapnik before we can play with new toys :-).

**Comment by wilhelmberg** [comment]
> We generate a ninja build file, using cmake 3.x with custom rules (we also generate SLN but I did not try to build with those).

I'm not familiar with ninja, but SLN/MSBuild combination might really be worth a try.
[libosmium](https://github.com/osmcode/libosmium) also uses CMake to generate project files, and I wasn't able to get it compile right with the generated Make files whereas the SLN works as expected.

> We still have a lot of other dependencies to rebuild besides mapnik before we can play with new toys :-).

Sure.
Just thought this might be of interest.

Ping me again for my email, if you are hitting a wall and there's a chance that you can share your build scripts with me privately, so that I can take a look.

**Comment by pmezard** [comment]
Building boost 1.55 with Visual Studio 2013 does not seem to be an option after all.

I tried the release build with PDB and it fails the same way than the debug one.

I will try to extract one cl.exe line and the link.exe call as well, maybe some options will catch your eye.

Also, do you know if mapnik 2.2.x can be built with boost 1.56 _without_ spirit v3? I added the define the same way the Scons script does to fix some compilation issue, but I am suspect it to cause the linker failure, so if there is another way...

**Comment by wilhelmberg** [comment]
> I tried the release build with PDB and it fails the same way than the debug one.

Too bad :cry: 
Maybe https://github.com/mapnik/mapnik/issues/2450 is causing this.
Although this issue should concern OSX and 3.x only and shouldn't cause anything with Release with PDB on Windows.

> Also, do you know if mapnik 2.2.x can be built with boost 1.56 without spirit v3?

No, I don't know.
Maybe @springmeyer could give his $0.02?

**Comment by pmezard** [comment]
Sorry for the late reply. While extracting the cl.exe and linker command lines I noticed it would be easy to drop the .pdb generation at link time as you suggested. It worked and I can now compile mapnik in debug and release mode without debug information, which is better than nothing.

Thank you for your help.

**Comment by wilhelmberg** [comment]
@pmezard Glad that it is working for you now. Thanks for getting back.
