### ISSUE TITLE
PostGIS connection with Mapnik and Tirex

### ISSUE THREAD

**Issue by kozyr** [mapnik/mapnik-support#44]
Hello,
I'm currently running a rendering server with Tirex and Mapnik 2.2 that just keeps rendering tiles from different PostGIS (Postgres 9.4 and Postgis 2.1) databases. PostGIS is running on a different server from Tirex/Mapnik.
I run 8 rendering processes for each of the 10 different cities (Tirex maps) that I'm rendering, and this results in 80 PostGIS connections on rendering startup. The whole setup mostly works, yet if it sits around for an hour or so without doing any rendering, any future jobs I submit get stuck and timeout, and after they timeout, I get following errors from Mapnik:
`Postgis Plugin: Bad connection Connection string: 'host=dbhost port=5432 dbname=mydb user=postgres connect_timeout=4'`

Looking at postgres, I can see 160 connection open at that time from Mapnik, and even though I've increased number of connections on Postgres to 500, I can't connect to Postgres from my rendering box anymore (neither with Mapnik nor with psql).

Any way I can "restart" these connections with Mapnik? Also, is the Mapnik postgis connection pool global? Could I limit number of connection that are being opened?

In terms of data load, the tables that contain my geometries are only about 500k rows, and both rendering and DB server run on fast 8 core boxes with over 20GB of RAM. The rendering is really fast when it works, the only issue is the timeout that happens after a period of inactivity and leads to `Bad connection` error.

**Comment by springmeyer** [comment]
Hi @kozyr - I think these hung connections are a bug in Mapnik 2.2 that is likely fixed in 3.x (or at least we've only had reports against 2.x: https://github.com/mapnik/mapnik/issues/2306).

So I would recommend upgrading to Mapnik 3.x and seeing if the problem persists. As far as tirex support for Mapnik 3.x, see https://github.com/openstreetmap/tirex/pull/3

**Comment by kozyr** [comment]
I'll try it out with Mapnik 3.0.1 :)
For anyone who's still stuck with 2.2 and has the same problem, I ended up setting these values in Postgres:

`tcp_keepalives_idle = 5
tcp_keepalives_interval = 5
tcp_keepalives_count = 2`

and this on mapnik:
`<Parameter name="persist-connection">false</Parameter>`
And since then I've been running tirex for weeks without restarts.

**Comment by springmeyer** [comment]
@kozyr - cool, can you explain more about why/how you think those settings worked around the problem?

**Comment by kozyr** [comment]
Postgres should be timing out idle connections very quickly with these settings, and then I assume Mapnik recreates them as necessary again.

**Comment by springmeyer** [comment]
@kozyr thanks. So are you aware of what the default timeout behavior is for postgres? Asking so I can figure out if we can close https://github.com/mapnik/mapnik/issues/2306.

**Comment by kozyr** [comment]
I think the default is to use the OS tcp timeout, and for Linux it's typically 2 hours.

**Comment by 3XE** [comment]
## Any chance of renewing interest in this?  TileStache is built on 2.2 and python-mapnik for 3.0 is not yet packaged.  I'm not sure if the [#issuecomment-117777926](https://github.com/mapnik/mapnik-support/issues/44#issuecomment-117777926) is the best solution for production tile severs because it means routing the requests via the TCP/IP stack and also keeping connections alive longer than absolutely necessary.

Peter

**Comment by roomit-xyz** [comment]
where is place parameter <Parameter name="persist-connection">false</Parameter> in mapnik stored in linux?
