### ISSUE TITLE
Having troubles with add_geospatial_pdf_header

### ISSUE THREAD

**Issue by mbonnefoy** [mapnik/mapnik-support#58]
Hi there,

I am working on converting some maps to PDF through mapnik. My code (simplified version) looks something like this:

```
m = mapnik.Map(100, 100)
# ... some basic styling there ...
m.zoom_to_box(mapnik.Box2d(1172741.51211,4999945.32251,1823068.11864,5651175.70809))   
page = mapnik.printing.PDFPrinter(pagesize=my_page_size, use_ocg_layers=True) # my_page_size is A4 format in meters 
page.render_map(m,"my_output_file.pdf")
page.finish()
page.add_geospatial_pdf_header(m, "my_output_file.pdf", epsg=my_epsg)
```

The map looks ok on my PDF but the geospatial info is wrong (checked on Acrobat geo tool and gdalinfo).

The issue seems to come from the /BBox PDF header. I get something like [0 0 0.2 0.2] whereas my /MediaBox PDF header is [ 0 0 595 841]. I tried to force my PDF header to the /MediaBox values and everything seemed to work fine. Having checked a couple of PDFs with correct geo headers, the /BBox and /MediaBox apparently always have similar values. 

Do you guys have any idea of what I could be doing wrong? I have been looking for it for hours but can't find a solution. I am a newbie in the mapnik world.

Thanks.

**Comment by springmeyer** [comment]
Hi @mbonnefoy. So, no I have no idea what is wrong. Mapnik actually does not know about the PDF/GeoPDF format at all. So the bug is likely inside the `PDFPrinter` code which is a separate python script that has been moved out of core (https://github.com/mapnik/mapnik/issues/2673). Currently it is at https://github.com/mapnik/python-mapnik/blob/master/mapnik/printing.py. I recommend you start to learn what it is doing in more detail. @thjc wrote `printing.py` and I'm not aware of anyone else that is familiar with the code. /cc @rcoup

**Comment by mbonnefoy** [comment]
Hi @springmeyer, @thjc,

Thanks for your feedback. The problem seems to be that the add_geospatial_pdf_header method does not convert the map_box from meters to pdf units (1 inch / 72) when assigning its values to the PDF bbox. 

changing from

<pre>
for x in self.map_box:
    bbox.append(pyPdf.generic.FloatObject(str(<b>x</b>)))
</pre>

to

<pre>
for x in self.map_box:
    bbox.append(pyPdf.generic.FloatObject(str(<b>m2pt(x)</b>)))
</pre>

seems to solve the problem for me.

**Comment by springmeyer** [comment]
@mbonnefoy great, want to supply that to `python-mapnik` with a testcase?

**Comment by mbonnefoy** [comment]
Hi @springmeyer, I am working on other changes too. Will propose those and that one soon. Thanks.
